version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_volume:/vol/web/media
      - static_volume:/vol/web/static
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend
    container_name: web

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/certs:/etc/ssl:ro
      - static_volume:/vol/web/static:ro
      - media_volume:/vol/web/media:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend: