# Generated by Django 5.2.3 on 2025-06-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('roles', '0001_initial'),
        ('tasks', '0006_assignedtask_taskprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('assigned_task', models.ForeignKey(help_text='Активная задача резидента на момент отчёта', on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='tasks.assignedtask')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='reports.residentreport')),
            ],
            options={
                'verbose_name': 'Комментарий к задаче',
                'verbose_name_plural': 'Комментарии к задачам',
                'unique_together': {('report', 'assigned_task')},
            },
        ),
        migrations.CreateModel(
            name='ResidentReportRoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('responsible', 'Ответственный'), ('irresponsible', 'Безответственный')], default='responsible', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_statuses', to='reports.residentreport')),
                ('role_assignment', models.ForeignKey(help_text='Активное назначение роли резиденту', on_delete=django.db.models.deletion.CASCADE, to='roles.residentroleassignment')),
            ],
            options={
                'verbose_name': 'Оценка роли резидента',
                'verbose_name_plural': 'Оценки ролей резидента',
                'unique_together': {('report', 'role_assignment')},
            },
        ),
    ]
