# Generated by Django 5.2.3 on 2025-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttaskcomment_residentreportrolestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentreport',
            name='usts_comment',
            field=models.TextField(blank=True, help_text='Комментарий по УСТС'),
        ),
        migrations.AddField(
            model_name='residentreport',
            name='usts_format_followed',
            field=models.BooleanField(default=False, help_text='Имеет ли формат УСТС'),
        ),
        migrations.AddField(
            model_name='residentreport',
            name='usts_info_shared',
            field=models.BooleanField(default=False, help_text='Информацию подает (ровно / не ровно)'),
        ),
    ]
