# Generated by Django 5.2.1 on 2025-05-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '__first__'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktemplate'),
        ),
    ]
