# Generated by Django 5.2.1 on 2025-06-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_type',
            field=models.CharField(choices=[('short_term', 'Краткосрочное'), ('long_term', 'Долгосрочное'), ('test', 'Тестовое')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AssignedTask',
        ),
    ]
