# Generated by Django 5.2.1 on 2025-06-11 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('tasks', '0003_remove_tasktemplate_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('writing_started', models.DateField(blank=True, help_text='Дата начала написания задания', null=True)),
                ('writing_finished', models.DateField(blank=True, help_text='Дата завершения написания', null=True)),
                ('submitting_started', models.DateField(blank=True, help_text='Дата начала сдачи', null=True)),
                ('completed_at', models.DateField(blank=True, help_text='Дата полного завершения задания', null=True)),
                ('status', models.CharField(choices=[('writing', 'Пишет'), ('submitting', 'Сдаёт'), ('completed', 'Завершено')], default='writing', max_length=20)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='residents.resident')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='tasks.tasktemplate')),
            ],
            options={
                'verbose_name': 'Назначенное задание',
                'verbose_name_plural': 'Назначенные задания',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text="Текущий этап выполнения (например, 'сдал', 'на проверке', 'отправлено')", max_length=255)),
                ('comment', models.TextField(blank=True, help_text='Комментарий консультанта или психолога по данному этапу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время, когда был зафиксирован этап')),
                ('resident', models.ForeignKey(help_text='Резидент, который выполняет задание', on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to='residents.resident')),
                ('template', models.ForeignKey(help_text='Шаблон задания, по которому идёт прогресс', on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='tasks.tasktemplate')),
            ],
            options={
                'verbose_name': 'Прогресс выполнения задания',
                'verbose_name_plural': 'Прогресс выполнения заданий',
                'ordering': ['created_at'],
            },
        ),
    ]
