# Generated by Django 5.2.1 on 2025-06-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_assignedtask_taskprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogress',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='template',
        ),
        migrations.DeleteModel(
            name='AssignedTask',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
