# Generated by Django 5.2.3 on 2025-07-19 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_assignedtask_taskprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
