# Generated by Django 5.2.1 on 2025-05-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_admission', models.DateField(verbose_name='Дата поступления')),
                ('dependency_type', models.CharField(choices=[('F10', 'Алкогольная зависимость (F10)'), ('F11', 'Опиоидная зависимость (F11)'), ('F12', 'Каннабиноидная зависимость (F12)'), ('F13', 'Седативная зависимость (F13)'), ('F14', 'Кокаиновая зависимость (F14)'), ('F15', 'Психостимуляторы (F15)'), ('F21', 'Шизотипическое расстройство (F21)'), ('F19', 'Множественные зависимости (F19)'), ('OTHER', 'Другое')], default='OTHER', max_length=10, verbose_name='Тип зависимости')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Резидент',
                'verbose_name_plural': 'Резиденты',
            },
        ),
    ]
