# Generated by Django 5.2.3 on 2025-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
