# Generated by Django 5.2.3 on 2025-07-20 00:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_alter_resident_options_remove_resident_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'default_manager_name': 'active', 'ordering': ['last_name', 'first_name'], 'verbose_name': 'Резидент', 'verbose_name_plural': 'Резиденты'},
        ),
        migrations.AlterModelManagers(
            name='resident',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
