# Generated by Django 5.2.3 on 2025-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_alter_resident_options_alter_resident_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('newbie', 'Новичок'), ('in_progress', 'Идущий'), ('advanced', 'Впереди идущий')], default='newbie', max_length=20, verbose_name='Статус'),
        ),
    ]
