# Generated by Django 5.2.1 on 2025-06-13 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_dailydynamics_emotionalstate_familyactivity_and_more'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('unassigned_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения роли')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий (необязательно)')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='residents.resident', verbose_name='Резидент')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='references.residentrole', verbose_name='Роль (функция)')),
            ],
            options={
                'verbose_name': 'Назначение роли резиденту',
                'verbose_name_plural': 'Назначения ролей резидентам',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
