# Generated by Django 5.2.3 on 2025-07-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentroleassignment',
            name='assigned_at',
            field=models.DateField(verbose_name='Дата назначения'),
        ),
    ]
