# Generated by Django 5.2.1 on 2025-05-28 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('strength', 'Достоинство'), ('defect', 'Дефект')], default='defect', max_length=10)),
                ('slug', models.SlugField(blank=True, help_text='Уникальный идентификатор для использования в коде, API и шаблонах', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Черта характера',
                'verbose_name_plural': 'Черты характера',
            },
        ),
        migrations.CreateModel(
            name='ResidentFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Функция резидента',
                'verbose_name_plural': 'Функции резидентов',
            },
        ),
        migrations.CreateModel(
            name='ResidentRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Уникальный идентификатор для использования в коде, API и шаблонах', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о назначении или функциях роли.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль резидента',
                'verbose_name_plural': 'Роли резидентов',
            },
        ),
    ]
