# Generated by Django 5.2.1 on 2025-05-28 23:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDynamics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Динамика',
                'verbose_name_plural': 'Динамика',
            },
        ),
        migrations.CreateModel(
            name='EmotionalState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Эмоциональное состояние',
                'verbose_name_plural': 'Эмоциональные состояния',
            },
        ),
        migrations.CreateModel(
            name='FamilyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Активность в семье',
                'verbose_name_plural': 'Активность в семье',
            },
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Мотивация',
                'verbose_name_plural': 'Мотивации',
            },
        ),
        migrations.CreateModel(
            name='MrpActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Активность на МРП',
                'verbose_name_plural': 'Активность на МРП',
            },
        ),
        migrations.CreateModel(
            name='PhysicalState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Физическое состояние',
                'verbose_name_plural': 'Физические состояния',
            },
        ),
        migrations.DeleteModel(
            name='ResidentFunction',
        ),
        migrations.AlterModelOptions(
            name='residentrole',
            options={'verbose_name': 'Функция резидента', 'verbose_name_plural': 'Функции резидентов'},
        ),
    ]
