# Generated by Django 5.2.3 on 2025-06-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_dailydynamics_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactertrait',
            name='score',
        ),
        migrations.AddField(
            model_name='emotionalstate',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='familyactivity',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='motivation',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='mrpactivity',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='physicalstate',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
